services:
  # Users Service
  users-service:
    build:
      context: ./fakestore-users-service
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PRODUCT_SERVICE_URL=${PRODUCT_SERVICE_URL}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    networks:
      - cloudstore-net

      # Product Service
  product-service:
    build:
      context: ./fakestore-product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWKS_URL=${JWKS_URL}
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
    networks:
      - cloudstore-net

  frontend:
    build:
      context: ./fakestore-frontend
      dockerfile: Dockerfile
    container_name: frontend-react
    ports:
      - "80:80"
    depends_on:
      - users-service
      - product-service
    networks:
      - cloudstore-net

networks:
  cloudstore-net:
    driver: bridge