server {
    listen 80;
    server_name ec2-13-61-35-20.eu-north-1.compute.amazonaws.com;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/users/ {
        proxy_pass http://ec2-13-51-166-242.eu-north-1.compute.amazonaws.com:8080/users/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/auth/request-token {
        proxy_pass http://ec2-13-51-166-242.eu-north-1.compute.amazonaws.com:8080/request-token;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /products/ {
        proxy_pass http://ec2-51-21-168-99.eu-north-1.compute.amazonaws.com:8081/products/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}